
package Gestor.Pantallas;

import Gestor.Entidades.Cita;
import Gestor.Entidades.Paciente;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Micha
 */
public class JFramePacientes extends javax.swing.JFrame {

    /**
     * Creates new form PantallPacientes
     */
      
    JFrameEditarCita padre;
    private DefaultListModel modeloListPacientes;
    static List<Paciente> listaPacientes = new ArrayList() ;
    public JFramePacientes(JFrameEditarCita padre) {
        initComponents();
        
        this.padre = padre;
        llenarJList();
    }
    public void llenarJList() {
        modeloListPacientes = new DefaultListModel();
        lstpacientes.setModel(modeloListPacientes);
        modeloListPacientes.removeAllElements();
         for (Paciente paciente : listaPacientes) {
           
            modeloListPacientes.addElement(paciente.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtbuscarpaciente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstpacientes = new javax.swing.JList<>();
        btnSalir = new javax.swing.JLabel();
        btnagregarPaciente = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pacientes");

        txtbuscarpaciente.setBackground(new java.awt.Color(255, 255, 255));
        txtbuscarpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarpacienteActionPerformed(evt);
            }
        });
        txtbuscarpaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarpacienteKeyTyped(evt);
            }
        });

        lstpacientes.setBackground(new java.awt.Color(255, 255, 255));
        lstpacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstpacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstpacientes);

        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.Cancelar.png"))); // NOI18N
        btnSalir.setText("Cancelar");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        btnagregarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnagregarPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnagregarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevacita.crear.guardar.png"))); // NOI18N
        btnagregarPaciente.setText("Crear paciente");
        btnagregarPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnagregarPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnagregarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregarPacienteMouseClicked(evt);
            }
        });

        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnagregarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(txtbuscarpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscarpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagregarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void addPaciente (Paciente paciente){
        listaPacientes.add(paciente);
    }
    private void txtbuscarpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarpacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarpacienteActionPerformed

    private void lstpacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstpacientesMouseClicked
        int indice = lstpacientes.getSelectedIndex();
        if(indice!=-1 && evt.getClickCount()==2){
            this.dispose();
            Paciente paciente = listaPacientes.get(indice);
            padre.addPaciente(paciente);
            padre.setVisible(true);
            
        }
       
       
        
    }//GEN-LAST:event_lstpacientesMouseClicked

    private void txtbuscarpacienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarpacienteKeyTyped
        // TODO add your handling code here:
        if(txtbuscarpaciente.getText().isEmpty())
        {
          llenarJList();
        }
    }//GEN-LAST:event_txtbuscarpacienteKeyTyped

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        this.dispose();
        padre.setVisible(true);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnagregarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarPacienteMouseClicked
        // TODO add your handling code here:
        JFrameAgregarPaciente agregarPaciente = new JFrameAgregarPaciente(this);
        agregarPaciente.setLocationRelativeTo(null);
        agregarPaciente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnagregarPacienteMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        modeloListPacientes.removeAllElements();
        for (Paciente paciente : listaPacientes) {
            if(paciente.getNombre().contains(txtbuscarpaciente.getText())){
                modeloListPacientes.addElement(paciente.toString());
            }
        }      
    }//GEN-LAST:event_btnBuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel btnagregarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstpacientes;
    private javax.swing.JTextField txtbuscarpaciente;
    // End of variables declaration//GEN-END:variables
}
