
package Gestor.Pantallas;

import Gestor.Entidades.Medico;
import Gestor.Entidades.Paciente;
import static Gestor.Pantallas.JFramePacientes.listaPacientes;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Micha
 */
public class JFrameMedicos extends javax.swing.JFrame {

    /**
     * Creates new form PantallaMedicos
     */
    JFrameEditarCita padre;
    static List<Medico> listaMedicos = new ArrayList();
    private DefaultListModel modeloListMedicos;
    public JFrameMedicos(JFrameEditarCita padre) {
        initComponents();
        this.padre = padre;
        llenarJList();
    }
    public void llenarJList() {
        modeloListMedicos = new DefaultListModel();
        lstMedicos.setModel(modeloListMedicos);
        modeloListMedicos.removeAllElements();
        for (Medico medico : listaMedicos) {           
            modeloListMedicos.addElement(medico.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtbuscarmedico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMedicos = new javax.swing.JList<>();
        btnSalir = new javax.swing.JLabel();
        btnagregarMedico = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Medicos");

        txtbuscarmedico.setBackground(new java.awt.Color(255, 255, 255));
        txtbuscarmedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarmedicoActionPerformed(evt);
            }
        });
        txtbuscarmedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarmedicoKeyTyped(evt);
            }
        });

        lstMedicos.setBackground(new java.awt.Color(255, 255, 255));
        lstMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstMedicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstMedicos);

        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.Cancelar.png"))); // NOI18N
        btnSalir.setText("Cancelar");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        btnagregarMedico.setForeground(new java.awt.Color(255, 255, 255));
        btnagregarMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnagregarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevacita.crear.guardar.png"))); // NOI18N
        btnagregarMedico.setText("Crear paciente");
        btnagregarMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnagregarMedico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnagregarMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregarMedicoMouseClicked(evt);
            }
        });

        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtbuscarmedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnagregarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscarmedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagregarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void addMedico(Medico medico){
        listaMedicos.add(medico);
    }
    
    private void txtbuscarmedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarmedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarmedicoActionPerformed

    private void lstMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstMedicosMouseClicked
        int indice = lstMedicos.getSelectedIndex();
        if(indice!=-1 && evt.getClickCount()==2){
            this.dispose();
            Medico medico = listaMedicos.get(indice);
            padre.addMedico(medico);
            padre.addFechaHora();
            padre.setVisible(true);
            
            
        }
    }//GEN-LAST:event_lstMedicosMouseClicked

    private void txtbuscarmedicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarmedicoKeyTyped
     
        if(txtbuscarmedico.getText().isEmpty())
        {
          llenarJList();
        }
    }//GEN-LAST:event_txtbuscarmedicoKeyTyped

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
       this.dispose();
        padre.setVisible(true);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnagregarMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMedicoMouseClicked
        JFrameAgregarMedico agregarMedico = new JFrameAgregarMedico(this);
        agregarMedico.setLocationRelativeTo(null);
        agregarMedico.setVisible(true);        
        this.setVisible(false);
    }//GEN-LAST:event_btnagregarMedicoMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        modeloListMedicos.removeAllElements();
        for (Medico medico : listaMedicos) {
            if(medico.getNombre().contains(txtbuscarmedico.getText())){
                modeloListMedicos.addElement(medico.toString());
            }
        } 
    }//GEN-LAST:event_btnBuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel btnagregarMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstMedicos;
    private javax.swing.JTextField txtbuscarmedico;
    // End of variables declaration//GEN-END:variables
}
