package Gestor.Pantallas;

import Gestor.Entidades.Cita;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
/**
 *
 * @author Micha
 */
public class JFrameGestorCitas extends javax.swing.JFrame {
    private static List<Cita> listaCitas = new ArrayList<Cita>();
    private DefaultListModel modeloListCitas;
    /**
     * Creates new form PantallaGestorCitas
     */
    public JFrameGestorCitas() {
        initComponents();
        llenarJList();  
    }
    private void llenarJList() {
        modeloListCitas = new DefaultListModel();
        JListCitas.setModel(modeloListCitas);
        modeloListCitas.removeAllElements();
         for (Cita cita : listaCitas) {
           
            modeloListCitas.addElement(cita.toString());
        }
    }
    public void addCita(Cita cita){
        listaCitas.add(cita);
        llenarJList();                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListCitas = new javax.swing.JList<>();
        btnCancelar = new javax.swing.JLabel();
        btnCrearCita = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));

        JListCitas.setBackground(new java.awt.Color(255, 255, 255));
        JListCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JListCitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JListCitas);

        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.Cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar cita");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        btnCrearCita.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCrearCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevacita.crear.guardar.png"))); // NOI18N
        btnCrearCita.setText("Nueva Cita");
        btnCrearCita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrearCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearCitaMouseClicked(evt);
            }
        });

        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(btnCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrearCita, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnCrearCita, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JListCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JListCitasMouseClicked
        // TODO add your handling code here:
        int indice = JListCitas.getSelectedIndex();
        if( indice!=-1 && evt.getClickCount() == 2){
            Cita cita = listaCitas.get(indice);
            JFrameEditarCita visualizarCita = new JFrameEditarCita(cita,this);
            visualizarCita.modificarFrame();
            visualizarCita.setLocationRelativeTo(null);
            visualizarCita.setSize(290,355);
            visualizarCita.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_JListCitasMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
       int indice = JListCitas.getSelectedIndex();
        if(indice!=-1){
            listaCitas.remove(indice);
            llenarJList();
            JOptionPane.showMessageDialog(null,
                    "Cita eliminada "
                    ,"Eliminar Cita", JOptionPane.INFORMATION_MESSAGE);
        }else{
             JOptionPane.showMessageDialog(null,
                     "Selecciona un cita de la lista"
                    ,"Eliminar Cita",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCrearCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearCitaMouseClicked
        // TODO add your handling code here:
        JFrameEditarCita nuevaCita = new JFrameEditarCita(this);
        nuevaCita.setLocationRelativeTo(null);
        nuevaCita.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCrearCitaMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        modeloListCitas.removeAllElements();
    for (Cita cita : listaCitas) {
        if (cita.getPaciente().getNombre().contains(txtBuscar.getText())) {
            modeloListCitas.addElement(cita.toString());
        }
    }
    }//GEN-LAST:event_btnBuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JListCitas;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnCrearCita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
