package Gestor.Pantallas;
import Gestor.Entidades.Especialidad;
import Gestor.Entidades.Medico;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Micha
 */
public class JFrameAgregarMedico extends javax.swing.JFrame {

    /**
     * Creates new form PantallaAgregarMedico
     */
    JFrameMedicos padre;
    Medico medico;
    List <Especialidad> listaespecialidad;
    public JFrameAgregarMedico(JFrameMedicos padre) {
        initComponents();
        listaespecialidad = new ArrayList<>();
        medico = new Medico();
        this.padre = padre;
    }
    private DefaultListModel modeloListMedicos;
   
    public void llenarJList() {
        modeloListMedicos = new DefaultListModel();
        lstespecialidades.setModel(modeloListMedicos);
        modeloListMedicos.removeAllElements();
        for (Especialidad especialidad : listaespecialidad) {
           
            modeloListMedicos.addElement(especialidad.getNombre());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombremedico = new javax.swing.JTextField();
        txtCMPmedico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstespecialidades = new javax.swing.JList<>();
        btnadd = new javax.swing.JButton();
        btnquitar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btncancelar = new javax.swing.JLabel();
        btnguardar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombremedico.setBackground(new java.awt.Color(255, 255, 255));

        txtCMPmedico.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Nombre:");

        jLabel3.setText("CMP:");

        jLabel1.setText("Agregar Medico");

        lstespecialidades.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(lstespecialidades);

        btnadd.setBackground(new java.awt.Color(0, 0, 255));
        btnadd.setText("+");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnquitar.setBackground(new java.awt.Color(255, 0, 0));
        btnquitar.setText("-");
        btnquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitarActionPerformed(evt);
            }
        });

        jLabel4.setText("Especialidades");

        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.Cancelar.png"))); // NOI18N
        btncancelar.setText("Cancelar ");
        btncancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelarMouseClicked(evt);
            }
        });

        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevacita.crear.guardar.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnguardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCMPmedico, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(txtNombremedico)))
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(btnquitar)
                                .addGap(5, 5, 5)
                                .addComponent(btnadd))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombremedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCMPmedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnquitar)
                    .addComponent(btnadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datosMedico() {
        String cmp =txtCMPmedico.getText();
        String nombre = txtNombremedico.getText();
        medico.setCMP(cmp);
        medico.setNombre(nombre);
        medico.setEspecialidades(listaespecialidad);
        padre.addMedico(medico);
    }

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String especialidadnombre = "";
        especialidadnombre =
                JOptionPane.showInputDialog(null, 
                        "Ingrese especialidad: "
                , "Agregar especialidad",0);
        if(!"".equals(especialidadnombre)){
            Especialidad especialidad = new Especialidad();
            especialidad.setNombre(especialidadnombre);
            listaespecialidad.add(especialidad);            
            llenarJList();
            
        }else{
            JOptionPane.showMessageDialog(null, 
                    "Debe ingresar una especialidad"
                    ,"Agregar especialidad", 
                    JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitarActionPerformed
        // TODO add your handling code here:
        int indice = lstespecialidades.getSelectedIndex();        
        if(indice!=-1){   
            listaespecialidad.remove(indice);
            llenarJList();                      
        }
        else{
            JOptionPane.showMessageDialog(null,
                    "Selecciones una especialidad de la lista"
                    ,"Eliminar especialidad",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnquitarActionPerformed

    private void btncancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelarMouseClicked
        // TODO add your handling code here:        
        this.dispose();
        padre.setVisible(true);
    }//GEN-LAST:event_btncancelarMouseClicked

    private void btnguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseClicked
        // TODO add your handling code here:
        if(!txtCMPmedico.getText().isEmpty() &&
            !txtNombremedico.getText().isEmpty()
            && !listaespecialidad.isEmpty()){
            datosMedico();
            this.dispose();
            padre.llenarJList();
            padre.setVisible(true);        
        }
        else{
              JOptionPane.showMessageDialog(null, "Completa todos "
                      + "los campos"
                    ,"Agregar"
                    + " Medico", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnguardarMouseClicked

    /**
     * @param args the command line argumentstxtCMP   
     * */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JLabel btncancelar;
    private javax.swing.JLabel btnguardar;
    private javax.swing.JButton btnquitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstespecialidades;
    private javax.swing.JTextField txtCMPmedico;
    private javax.swing.JTextField txtNombremedico;
    // End of variables declaration//GEN-END:variables
}
