
package Gestor.Pantallas;

import Gestor.Entidades.Cita;
import Gestor.Entidades.Especialidad;
import Gestor.Entidades.Medico;
import Gestor.Entidades.Paciente;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Micha
 */
public class JFrameEditarCita extends javax.swing.JFrame {

    /**
     * Creates new form JFrameEditarCita
     */
    JFrameGestorCitas padre;
    Cita cita;
    Medico medico = null;
    Paciente paciente = null;
    Especialidad especialidad;
    public JFrameEditarCita(JFrameGestorCitas padre) {
        initComponents();
        this.padre = padre;
    }
    public JFrameEditarCita(Cita cita, JFrameGestorCitas padre){
        initComponents();
       
        this.cita = cita;
        this.padre = padre;
    }
    public void modificarFrame(){
        lbltitulo.setText("Visualizar Cita");
        hideControls();
        setData();
   }

    public void setData() {
        txtMedico.setText(cita.getMedico().getNombre());
        txtPaciente.setText(cita.getPaciente().getNombre());
        cbHora.addItem(cita.getHora());
        cbFecha.addItem(cita.getFecha());
        cbEspecialidad.addItem(cita.getEspecialida().getNombre());
    }

    public void hideControls() {
        btnGuardar.setVisible(false);
        btnMedico.setVisible(false);
        btnPaciente.setVisible(false);
    }
    public void addFechaHora(){
        generarFechaAleatoria();
        generarHoraAleatoria();  
    }

    private void generarFechaAleatoria() {
        Random random = new Random();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        Calendar fecha = Calendar.getInstance();
        fecha.set(2023, 5, random.nextInt(22));        
        for (int i = 0; i < 7; i++) {
            cbFecha.addItem(formatoFecha.format(fecha.getTime()));
            fecha.add(Calendar.DAY_OF_MONTH, 1);
        }
    }

    private void generarHoraAleatoria() {
        SimpleDateFormat formatoHora = new SimpleDateFormat("h:mm a");
        Calendar hora = Calendar.getInstance();
        hora.set(Calendar.HOUR_OF_DAY, 8);
        hora.set(Calendar.MINUTE, 0);
        hora.set(Calendar.SECOND, 0);        
        while (hora.get(Calendar.HOUR_OF_DAY) <= 14) {
            cbHora.addItem(formatoHora.format(hora.getTime()));
            hora.add(Calendar.MINUTE, 30);
        }
    }
    public void addPaciente(Paciente paciente){
        this.paciente = paciente;
        txtPaciente.setText(paciente.getNombre());
    }
    public void addMedico(Medico medico){
        this.medico = medico;      
        txtMedico.setText(medico.getNombre());
        for (Especialidad esp : medico.getEspecialidades()) {
            cbEspecialidad.addItem(esp.getNombre());           
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo = new javax.swing.JLabel();
        cbFecha = new javax.swing.JComboBox<>();
        cbHora = new javax.swing.JComboBox<>();
        cbEspecialidad = new javax.swing.JComboBox<>();
        txtPaciente = new javax.swing.JTextField();
        txtMedico = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JLabel();
        btnPaciente = new javax.swing.JLabel();
        btnMedico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo.setText("Nueva Cita");

        cbFecha.setBackground(new java.awt.Color(255, 255, 255));

        cbHora.setBackground(new java.awt.Color(255, 255, 255));

        cbEspecialidad.setBackground(new java.awt.Color(255, 255, 255));
        cbEspecialidad.setForeground(new java.awt.Color(0, 0, 0));
        cbEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspecialidadActionPerformed(evt);
            }
        });

        txtPaciente.setEditable(false);
        txtPaciente.setBackground(new java.awt.Color(255, 255, 255));

        txtMedico.setEditable(false);
        txtMedico.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Paciente");

        jLabel2.setText("Medico");

        jLabel3.setText("Especialidad");

        jLabel4.setText("Fecha");

        jLabel5.setText("Hora");

        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.Cancelar.png"))); // NOI18N
        btnSalir.setText("Cancelar cita");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevacita.crear.guardar.png"))); // NOI18N
        btnGuardar.setText("Crear Cita");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        btnPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BuscarP.M.png"))); // NOI18N
        btnPaciente.setText("Buscar Paciente");
        btnPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPacienteMouseClicked(evt);
            }
        });

        btnMedico.setForeground(new java.awt.Color(255, 255, 255));
        btnMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BuscarP.M.png"))); // NOI18N
        btnMedico.setText("Buscar Medico");
        btnMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMedicoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(cbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datosCita() {
        Cita cita = new Cita();
        cita.setMedico(medico);
        cita.setPaciente(paciente);
        cita.setFecha(cbFecha.getSelectedItem().toString());
        cita.setHora(cbHora.getSelectedItem().toString());
        cita.setEspecialida(especialidad);
        padre.addCita(cita);
    }

    private void cbEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspecialidadActionPerformed
        // TODO Agrega aquí tu código de manejo del evento:
    String especialidadSeleccionada = (String) cbEspecialidad.getSelectedItem();
    String especialidadIngresada = cbEspecialidad.getEditor().getItem().toString().trim();

    }//GEN-LAST:event_cbEspecialidadActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
        padre.setVisible(true);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        if(medico!=null && paciente != null){
            especialidad = new Especialidad();
            especialidad.setNombre(cbEspecialidad.getSelectedItem().toString());
            datosCita();
            this.dispose();
            padre.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,
                "Completa todos los campos"
                ,"Agregar Cita",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPacienteMouseClicked
        // TODO add your handling code here:
        JFramePacientes insertarPaciente = new JFramePacientes(this);
        insertarPaciente.setLocationRelativeTo(null);
        insertarPaciente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPacienteMouseClicked

    private void btnMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicoMouseClicked
       JFrameMedicos insertarMedico = new JFrameMedicos(this);
        insertarMedico.setLocationRelativeTo(null);
        insertarMedico.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMedicoMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel btnMedico;
    private javax.swing.JLabel btnPaciente;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JComboBox<String> cbEspecialidad;
    private javax.swing.JComboBox<String> cbFecha;
    private javax.swing.JComboBox<String> cbHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
